spring.application.name=backend

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
#parametrizar la URL y el usuario
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3309/vehiculos_db}
spring.datasource.username=${DB_USER:root}
# La contraseña ahora se leerá de la variable de entorno DB_PASS. 
# Si no la encuentra, usará "password_root" por defecto.
spring.datasource.password=${DB_PASS:password_root}
#esto es solo para entorno local! lo hice pensando en eso, no en un servidor publico.
#ahí sería otro el procedimiento
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.org.springframework.web=trace
logging.level.org.hibernate=trace
logging.level.com=TRACE
logging.file.name=backend.log
server.port=8180
jwt.secret=${JWT_SECRET:ZnJhc2VzbGFyZ2FzcGFyYWNvbG9jYXJjb21vY2xhdmVlbnVucHJvamVjdG9kZWVtZXBsb3BhcmFqd3Rjb25zcHJpbmdzZWN1cml0eQ==bWlwcnVlYmFkZWVqbXBsb3BhcmFiYXNlNjQ=}